package com.loizenai.jwtauthentication.model;

public enum  RoleName {
    ROLE_USER,
    ROLE_ACHETEUR,
    ROLE_TRANSITAIRE,
    ROLE_CLIENT,
    ROLE_VENDEUR,
    ROLE_DECIDEUR_BP,
    ROLE_AGENT_CAB,
    ROLE_PREPARATEUR_BR,
    ROLE_RESPONSABLE_DISPATCHING_BP,
    ROLE_PREPARATEUR,
    ROLE_VALIDATEUR_DE_CHARIOT,
    ROLE_RESPONSABLE_POINTAGE,
    ROLE_EMBALLEUR,
    ROLE_EXPEDITEUR,
    ROLE_AGENT_SAISIE_REG,
    ROLE_CAISSIER,
    ROLE_RESPONSABLE_SERVICE_FRS_ETRANGER,
    ROLE_RESPONSABLE_SERVICE_FRS_LOCAL,
    ROLE_ADMIN
}